function lutIlkle()
global lut
lut = {};

% yaris
lut{end+1} = lutElemaniOlustur('Sehir',true,{});
lut{end+1} = lutElemaniOlustur('YarisGunNo',false,{});
lut{end+1} = lutElemaniOlustur('Tarih',false,{});

% kosu
lut{end+1} = lutElemaniOlustur('KosuNo',true,{... 
    lutElemaniOlustur('KosuNo',false,{}),...
    lutElemaniOlustur('Saat',false,{}),...
%     lutElemaniOlustur('AltiliGanyanSiraSay',false,{}),...
    });
lut{end+1} = lutElemaniOlustur('KosuCinsi',true,{...
    lutElemaniOlustur('KosuCinsi',true,{}),...
    lutElemaniOlustur('Diþi',false,{}),...
    lutElemaniOlustur('Y1',false,{}),...
    lutElemaniOlustur('Y2',false,{}),...
    lutElemaniOlustur('Y3',false,{}),...
    });
lut{end+1} = lutElemaniOlustur('Grup',true,{...
    lutElemaniOlustur('GrupYas',true,{}),...
    lutElemaniOlustur('GrupCins',true,{}),...
    });
lut{end+1} = lutElemaniOlustur('Agirlik',false,{});
lut{end+1} = lutElemaniOlustur('Mesafe',false,{});
lut{end+1} = lutElemaniOlustur('Pist',true,{});

% at
lut{end+1} = lutElemaniOlustur('At No',false,{});
lut{end+1} = lutElemaniOlustur('At Ýsmi',true,{
    lutElemaniOlustur('Isim',true,{}),...
    lutElemaniOlustur('KG',false,{}),...
    lutElemaniOlustur('K',false,{}),...
    lutElemaniOlustur('SK',false,{}),...
    lutElemaniOlustur('SKG',false,{}),...
    lutElemaniOlustur('DB',false,{}),...
%     lutElemaniOlustur('YP',false,{}),... % yanak pelusu
    });
lut{end+1} = lutElemaniOlustur('Yaþ',true,{
    lutElemaniOlustur('Yas',false,{}),...
    lutElemaniOlustur('Renk',true,{}),...
    lutElemaniOlustur('Cinsiyet',false,{}),...
    });
lut{end+1} = lutElemaniOlustur('Orijin(Baba)',true,{
    lutElemaniOlustur('Isim',true,{}),...
    lutElemaniOlustur('UlkeOrijin',true,{}),...
    });
lut{end+1} = lutElemaniOlustur('Orijin(Anne)',true,{
    lutElemaniOlustur('Isim',true,{}),...
    lutElemaniOlustur('UlkeOrijin',true,{}),...
    });
lut{end+1} = lutElemaniOlustur('Kilo',false,{});
lut{end+1} = lutElemaniOlustur('Jokey Adý',true,{});
lut{end+1} = lutElemaniOlustur('Sahip Adý',true,{});
lut{end+1} = lutElemaniOlustur('Antrenör Adý',true,{});
lut{end+1} = lutElemaniOlustur('HK',false,{});
lut{end+1} = lutElemaniOlustur('Derece',false,{});
lut{end+1} = lutElemaniOlustur('Ganyan',false,{});
% lut{end+1} = lutElemaniOlustur('Fark',false,{});

